### ISSUE TITLE
Reading Tomo

### ISSUE THREAD

**Issue by onagat** [onagat/mcl-react#7]
- [x] form, validation (template driven, model driven) for #4 
- [x] RxJS
- [x] React with Firebase for #6 
- [x] Firebase CRUD for #4
